[package]
name = "marty_plugin_protocol"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow.workspace = true
