[package]
name = "marty-plugin-python-example"
version = "0.1.0"
edition = "2021"

[workspace]
# Empty workspace to make this standalone

[lib]
crate-type = ["cdylib"]

[dependencies]
marty_plugin_protocol = { path = "../../crates/plugin_protocol" }
serde_json = "1.0"
